version: '3.7'

services:
  influxdb:
    image: influxdb:2.7.1
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./data/influx/data:/var/lib/influxdb2
      - ./data/influx/config:/config
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME
      - DOCKER_INFLUXDB_INIT_ORG
      - DOCKER_INFLUXDB_INIT_BUCKET
      - DOCKER_INFLUXDB_INIT_PASSWORD
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
    env_file:
      - .env

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD
    env_file:
      - .env
    volumes:
      - ./data/grafana/data:/var/lib/grafana

  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
    - "27017:27017"
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./data/mongo:/data/db
